apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
spec:
  replicas: 3
  selector:
    app: rishijavaapp
  template:
    metadata:
      labels:
        app: rishijavaaap
    spec:
      containers:
      - name: containerx
        image: nginx
        ports:
      - containerPort: 80
